require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DishesController do
  include Devise::TestHelpers

  before (:each) do
    @user = Factory.create(:user)
    sign_in @user
  end

  def mock_dish(stubs={})
    @mock_dish ||= mock_model(Dish, stubs).as_null_object
  end

  describe "GET show" do
    it "assigns the requested dish as @dish" do
      Dish.stub(:find).with("37") { mock_dish }
      get :show, :id => "37"
      assigns(:dish).should be(mock_dish)
    end
  end

  describe "GET rate" do
    it "should rate the dish" do
      @request.env['HTTP_REFERER'] = 'http://can.i.net'

      @current_user = mock_model(User, :id => 1)
      controller.stub!(:current_user).and_return(@current_user)

      Dish.stub(:find).with("1") {mock_dish}
      User.stub(:find).with("1") {mock_user}
      mock_dish.should_receive(:rate!).with(2, @current_user)
      get :rate, id: "1", rating: "2"
    end
  end

end