require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DishesController do
  include Devise::TestHelpers

  before (:each) do
    @user = Factory.create(:user)
    sign_in @user
  end

  def mock_dish(stubs={})
    @mock_dish ||= mock_model(Dish, stubs).as_null_object
  end

  describe "GET show" do
    it "assigns the requested dish as @dish" do
      Dish.stub(:find).with("37") { mock_dish }
      get :show, :id => "37"
      assigns(:dish).should be(mock_dish)
    end
  end

  describe "GET rate" do
    it "should rate the dish" do
      @request.env['HTTP_REFERER'] = 'http://can.i.net'

      dish = mock_model(Dish, :id => 1, :serve_date => Time.now.to_date)

      Dish.stub(:find).with("1").and_return(dish)

      dish.should_receive(:rate!).with(2, @user)
      get :rate, id: "1", rating: "2"
    end
  end

end