require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MensasController do
  include Devise::TestHelpers

  before (:each) do
    @user = Factory.create(:user)
    sign_in @user
  end

  def mock_mensa(stubs={})
    @mock_mensa ||= mock_model(Mensa, stubs).as_null_object
  end

  describe "GET show" do
    it "assigns the requested mensa as @mensa" do
      Mensa.stub(:find).with("37") { mock_mensa }
      get :show, :id => "37"
      assigns(:mensa).should be(mock_mensa)
    end
  end

end
